<?xml version="1.0" encoding="UTF-8"?>
<definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://soap-calculator-x9mg.onrender.com"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="http://soap-calculator-x9mg.onrender.com"
    name="CalculatorService">

  <types>
    <xsd:schema targetNamespace="http://soap-calculator-x9mg.onrender.com">
      <xsd:element name="addRequest">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="number1" type="xsd:int"/>
            <xsd:element name="number2" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="addResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="result" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="subtractRequest">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="number1" type="xsd:int"/>
            <xsd:element name="number2" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="subtractResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="result" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </types>

  <message name="AddRequest">
    <part name="parameters" element="tns:addRequest"/>
  </message>
  <message name="AddResponse">
    <part name="parameters" element="tns:addResponse"/>
  </message>

  <message name="SubtractRequest">
    <part name="parameters" element="tns:subtractRequest"/>
  </message>
  <message name="SubtractResponse">
    <part name="parameters" element="tns:subtractResponse"/>
  </message>

  <portType name="CalculatorPortType">
    <operation name="add">
      <input message="tns:AddRequest"/>
      <output message="tns:AddResponse"/>
    </operation>
    <operation name="subtract">
      <input message="tns:SubtractRequest"/>
      <output message="tns:SubtractResponse"/>
    </operation>
  </portType>

  <binding name="CalculatorBinding" type="tns:CalculatorPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="add">
      <soap:operation soapAction="http://soap-calculator-x9mg.onrender.com/add"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
    <operation name="subtract">
      <soap:operation soapAction="http://soap-calculator-x9mg.onrender.com/subtract"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="CalculatorService">
    <port name="CalculatorPort" binding="tns:CalculatorBinding">
      <soap:address location="https://soap-calculator-x9mg.onrender.com/calculator"/>
    </port>
  </service>

</definitions>
